---
$schema: https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/eslintrc.json
root: true
ignorePatterns:
  - ./node_modules/**
env:
  browser: true
  es2022: true
  node: true
  worker: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
settings:
  jsdoc:
    mode: 'typescript'
overrides:
  - files:
      - '*.ts'
    parser: '@typescript-eslint/parser'
    parserOptions:
      ecmaVersion: latest
      sourceType: module
      project:
        - ./tsconfig.linter.json
      createDefaultProgram: true
    plugins:
      - '@typescript-eslint'
      - prettier
      - jsdoc
      - deprecation
      - editorconfig
      - ban
      - import
      - unused-imports
    extends:
      - prettier
    rules:
      '@typescript-eslint/array-type':
        - error
        - default: array
      '@typescript-eslint/ban-types':
        - error
        - types:
            Object:
          extendDefaults: false
      '@typescript-eslint/consistent-type-definitions': error
      '@typescript-eslint/consistent-type-assertions': error
      '@typescript-eslint/explicit-member-accessibility':
        - error
        - accessibility: explicit
          overrides:
            constructors: 'off'
      '@typescript-eslint/member-ordering':
        - error
      '@typescript-eslint/no-empty-function': error
      '@typescript-eslint/no-empty-interface': error
      '@typescript-eslint/no-inferrable-types': 'off'
      '@typescript-eslint/no-require-imports': error
      '@typescript-eslint/no-unnecessary-boolean-literal-compare': error
      '@typescript-eslint/no-unnecessary-type-assertion': error
      '@typescript-eslint/no-unused-expressions': error
      '@typescript-eslint/no-var-requires': error
      '@typescript-eslint/prefer-for-of': error
      '@typescript-eslint/prefer-readonly': error
      '@typescript-eslint/quotes':
        - error
        - single
      '@typescript-eslint/restrict-plus-operands': error
      '@typescript-eslint/strict-boolean-expressions':
        - error
        - allowString: false
          allowNumber: false
          allowRuleToRunWithoutStrictNullChecksIKnowWhatIAmDoing: true
      '@typescript-eslint/typedef':
        - error
        - arrowParameter: true
          arrayDestructuring: false
          memberVariableDeclaration: true
          objectDestructuring: false
          parameter: true
          propertyDeclaration: true
          variableDeclaration: true
          variableDeclarationIgnoreFunction: true
      '@typescript-eslint/type-annotation-spacing': error
      '@typescript-eslint/explicit-function-return-type':
        - error
        - allowExpressions: true
      '@typescript-eslint/no-namespace': off
      '@typescript-eslint/dot-notation': error
      '@typescript-eslint/no-dynamic-delete': error
      '@typescript-eslint/unified-signatures': off
      '@typescript-eslint/semi':
        - error
        - always
      '@typescript-eslint/no-extra-semi': error
      '@typescript-eslint/naming-convention':
        - error
        - selector: default
          format:
            - camelCase
          filter:
            regex: '^___.*'
            match: false
        - selector: variable
          format:
            - camelCase
            - UPPER_CASE
        - selector: enumMember
          format:
            - camelCase
            - PascalCase
        - selector: class
          format:
            - PascalCase
        - selector: typeLike
          format:
            - PascalCase
        - selector: classProperty
          format:
            - camelCase
          leadingUnderscore: allow
        - selector: objectLiteralProperty
          format:
            - camelCase
            - PascalCase
            - UPPER_CASE
          filter:
            regex: '^___.*'
            match: false
        - selector: typeProperty
          format:
            - camelCase
            - PascalCase
            - UPPER_CASE
          filter:
            regex: '^___.*'
            match: false
        - selector: function
          format:
            - camelCase
            - PascalCase
          modifiers:
            - exported
        - selector: parameter
          format:
            - camelCase
          leadingUnderscore: allow
        - selector: interface
          format:
            - PascalCase
          custom:
            regex: '^I[A-Z]'
            match: false
      'jsdoc/check-access': off
      'jsdoc/check-alignment': error
      'jsdoc/check-examples': off
      'jsdoc/check-indentation': error
      'jsdoc/check-line-alignment': error
      'jsdoc/check-param-names': error
      'jsdoc/check-property-names': error
      'jsdoc/check-syntax': error
      'jsdoc/check-tag-names': error
      'jsdoc/check-types': error
      'jsdoc/check-values': error
      'jsdoc/empty-tags': error
      'jsdoc/implements-on-classes': error
      'jsdoc/match-description': error
      'jsdoc/multiline-blocks': error
      'jsdoc/newline-after-description': error
      'jsdoc/no-bad-blocks': error
      'jsdoc/no-defaults': error
      'jsdoc/no-missing-syntax': off
      'jsdoc/no-multi-asterisks': error
      'jsdoc/no-restricted-syntax': off
      'jsdoc/no-types': error
      'jsdoc/no-undefined-types': error
      'jsdoc/require-asterisk-prefix': error
      'jsdoc/require-description': off
      'jsdoc/require-description-complete-sentence': error
      'jsdoc/require-example': off
      'jsdoc/require-file-overview':
        - error
        - tags:
            file:
              mustExist: false
      'jsdoc/require-hyphen-before-param-description': error
      'jsdoc/require-jsdoc': error
      'jsdoc/require-param': off
      'jsdoc/require-param-description': off
      'jsdoc/require-param-name': off
      'jsdoc/require-param-type': off
      'jsdoc/require-property': error
      'jsdoc/require-property-description': error
      'jsdoc/require-property-name': error
      'jsdoc/require-property-type': error
      'jsdoc/require-returns': off
      'jsdoc/require-returns-check': off
      'jsdoc/require-returns-description': off
      'jsdoc/require-returns-type': off
      'jsdoc/require-throws': off
      'jsdoc/require-yields': error
      'jsdoc/require-yields-check': error
      'jsdoc/tag-lines': error
      'jsdoc/valid-types': error
      complexity:
        - error
        - max: 30
      consistent-return: error
      constructor-super: error
      no-underscore-dangle: error
      default-case: error
      default-case-last: error
      eqeqeq:
        - error
        - always
      import/order:
        - error
        - newlines-between: never
          alphabetize:
            order: asc
      import/no-default-export: error
      max-len:
        - error
        - code: 120
          ignoreTemplateLiterals: true
          ignoreStrings: true
      no-caller: error
      no-duplicate-case: error
      no-duplicate-imports: error
      no-empty: error
      no-sequences:
        - error
        - allowInParentheses: false
      no-multi-spaces: error
      no-sparse-arrays: error
      no-template-curly-in-string: error
      prefer-object-spread: error
      use-isnan: error
      prefer-template: error
      object-shorthand: error
      quote-props:
        - error
        - 'as-needed'
      no-shadow: 'off'
      '@typescript-eslint/no-shadow': error
      no-throw-literal: 'off'
      '@typescript-eslint/no-throw-literal': error
      no-unused-vars: 'off'
      '@typescript-eslint/no-unused-vars':
        - error
        - argsIgnorePattern: '^_'
      no-var: error
      no-fallthrough: error
      no-trailing-spaces: error
      no-unneeded-ternary: error
      no-undef-init: error
      no-new-wrappers: error
      no-bitwise: error
      no-debugger: error
      spaced-comment:
        - error
        - always
        - markers:
            - '/'
      prefer-const: error
      eol-last: error
      radix: error
      no-eval: error
      no-console:
        - error
        - allow:
            - warn
      id-denylist:
        - error
        - callback
        - name
        - item
        - id
        - i
      arrow-body-style:
        - error
        - as-needed
      prettier/prettier:
        - error
      deprecation/deprecation: warn
      editorconfig/charset: error
      unused-imports/no-unused-imports: error
