---
$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: '0.2'
language: en
import:
  - '@cspell/dict-lorem-ipsum/cspell-ext.json'
ignorePaths:
  - node_modules
  - dist
  - coverage
dictionaries:
  - en_US
  - en-gb
  - companies
  - softwareTerms
  - misc
  - typescript
  - node
  - html
  - css
  - bash
  - fonts
  - filetypes
  - npm
  - lorem-ipsum
words:
  - unnested
  - ESBuild
  - Fedor
  - Usakov
  - AutoFix
  - outdir
  - lowcode
